# testo = "The Go Natural English method is best for learners who are self-motivated and willing to do the work to apply the method in everyday life. It is best for the intermediate learner who has some understanding of English already. Step one is to understand the method. Step two is to apply it! This book is not for someone who wants to become fluent in English overnight. Although it is true that with 15 minutes a day of focused effort you can improve your fluency, we don ’ t mean just one day. Improvements come with consistent effort over time. In fact, we encourage you to look at English fluency as a lifelong journey and not just a destination. Please understand that there is no magic pill for fluency. You must follow the steps in this book and do the exercises in order to see improvement. However, it should be fun, enjoyable and 15 minutes should go by quickly! Be patient"
# lista = ['The', 'Go', 'Natural', 'English', 'method', 'is', 'best', 'for', 'learners', 'who', 'are', 'self-motivated', 'and', 'willing', 'to', 'do', 'the', 'work', 'to', 'apply', 'the', 'method', 'in', 'everyday', 'life.', 'It', 'is', 'best', 'for', 'the', 'intermediate', 'learner', 'who', 'has', 'some', 'understanding', 'of', 'English', 'already.', 'Step', 'one', 'is', 'to', 'understand', 'the', 'method.', 'Step', 'two', 'is', 'to', 'apply', 'it!', 'This', 'book', 'is', 'not', 'for', 'someone', 'who', 'wants', 'to', 'become', 'fluent', 'in', 'English', 'overnight.', 'Although', 'it', 'is', 'true', 'that', 'with', '15', 'minutes', 'a', 'day', 'of', 'focused', 'effort', 'you', 'can', 'improve', 'your', 'fluency,', 'we', 'don', '’', 't', 'mean', 'just', 'one', 'day.', 'Improvements', 'come', 'with', 'consistent', 'effort', 'over', 'time.', 'In', 'fact,', 'we', 'encourage', 'you', 'to', 'look', 'at', 'English', 'fluency', 'as', 'a', 'lifelong', 'journey', 'and', 'not', 'just', 'a', 'destination.', 'Please', 'understand', 'that', 'there', 'is', 'no', 'magic', 'pill', 'for', 'fluency.', 'You', 'must', 'follow', 'the', 'steps', 'in', 'this', 'book', 'and', 'do', 'the', 'exercises', 'in', 'order', 'to', 'see', 'improvement.', 'However,', 'it', 'should', 'be', 'fun,', 'enjoyable', 'and', '15', 'minutes', 'should', 'go', 'by', 'quickly!', 'Be', 'patient']
# textlist = testo.split()
# print (textlist)
# print(len(textlist))
# testo.count("a")
# print('----------------')

# s1='abcdefghijklmopqrstuvwxyz'
# for x in range(len(s1)):
#      print(s1[x:x+1])

